version: '3.8'
services:
  app1:
    build: ./app1
    ports:
      - "3001:3000"
    container_name: app1

  app2:
    build: ./app2
    ports:
      - "3002:3000"
    container_name: app2

  app3:
    build: ./app3
    ports:
      - "3003:3000"
    container_name: app3
